### ISSUE TITLE
关于指定覆盖率统计文件或目录的功能 coverpkg

### ISSUE THREAD

**Issue by chengaomin** [qiniu/goc#100]
在使用go test 做覆盖率时，有go test -coverpkg可以指定覆盖率只统计哪些目录。
在goc里面，未找到此功能，是否有计划支持。

**Comment by CarlJi** [comment]
参考-coverpkg的语义:https://github.com/golang/go/blob/master/src/cmd/go/internal/test/test.go#L230

是个挺实用的功能。个人认为，可以从以下两个方面来支持:
1. `goc profile` 支持该参数-coverpkg。基本逻辑是先从`goc server`拿到覆盖率结果，然后通过-coverpkg来做过滤。使用姿势应如: `goc profile -coverpkg pattern`
2. `goc build/install` 支持该参数-coverpkg，支持在插桩时有选择性的插桩。比如 `goc build -coverpkg pattern ./...` 。其弊端是，没被插桩的包就会没办法拿到覆盖率结果了。

考虑到灵活性，个人倾向于选择第一种方式。

cc @lyyyuna  @chengaomin

**Comment by chengaomin** [comment]
1、第一种方式我认同，当前也是自己把profile后的文件自己filter的。
2、我还在思考一个问题，现在是全量插桩，如果提供了build的时候可以选择性插桩，那么build的时间上，是否会缩短，说不定也是一个不错的可以优化的点。

**Comment by CarlJi** [comment]
> 2、我还在思考一个问题，现在是全量插桩，如果提供了build的时候可以选择性插桩，那么build的时间上，是否会缩短，说不定也是一个不错的可以优化的点。

时间会有缩短。你这边是觉得`go build`时间过长吗？是否能介绍下是怎样规模的项目，`go build` 耗时多久呢？ @chengaomin

**Comment by chengaomin** [comment]
我这里其实也没有太久，30s到120s之间。

**Comment by sisyruan** [comment]
想问下这个指定覆盖率统计文件考虑什么时候支持呀
