### ISSUE TITLE
期望支持 PersistenceFile 可配置

### ISSUE THREAD

**Issue by Naisisor** [qiniu/goc#108]
https://github.com/qiniu/goc/blob/4b184c9fb5222e4a9d20767cb6b9a9848a4c7ff6/pkg/cover/store.go#L48
背景：如果 go server 部署在 K8s 集群中当服务宕机重启后无法做到持久化
目标：在 K8s 集群中希望将文件通过 hostPath 或者 OSS 这种方式挂载实现持久化存储亦或是使用 ConfigMap
需求：
希望在 goc server 启动服务的时候增加 PersistenceFile 参数，如：goc server --port=:8080 --register-path=<persistence-file-path/register.txt>

**Comment by CarlJi** [comment]
Good Idea, we will consider it.

**Comment by CarlJi** [comment]
The fix #120 provide a way to let user save the persistent file via hostPath. For the way about ConfigMap which actually need the `goc` deeply integrate with Kubernetes client, i think it is probably too heavy.

let‘s close this issue now, and feel free to reopen or create a new one if you have any more questions. @Naisisor
