### ISSUE TITLE
服务监听固定端口--agentport参数貌似没有生效？

### ISSUE THREAD

**Issue by sanren99999** [qiniu/goc#121]
各位贡献者，你们好！
这是一个超棒的工具！
我在使用的过程中，发现我设定固定监听端口没有生效，我是这样的一个过程：
1、首先启动server
![image](https://user-images.githubusercontent.com/5664399/94343852-b7bc8800-004d-11eb-8850-a235946d37ae.png)
2、执行命令goc build  --agentport :8080  --debug .
![image](https://user-images.githubusercontent.com/5664399/94343897-f9e5c980-004d-11eb-8406-9c8edd8c54db.png)
3、goc run .
![image](https://user-images.githubusercontent.com/5664399/94343915-1bdf4c00-004e-11eb-897a-892e0c3ab516.png)
发现端口还是随机生成的54776，并不是刚才注册的8080端口。

是不是我漏掉了某些步骤？
然后我有用goc init重置配置，具体步骤如下：
1、执行goc init
![image](https://user-images.githubusercontent.com/5664399/94343963-82fd0080-004e-11eb-9267-33961df91dbd.png)
2、执行goc register -a "http://127.0.0.1:8080" -n simple-go-server  --debug
![image](https://user-images.githubusercontent.com/5664399/94343994-ab84fa80-004e-11eb-9418-b1f556829fd3.png)
3、然后再执行 goc build  --agentport :8080  --debug . && goc run . 
![image](https://user-images.githubusercontent.com/5664399/94344030-ed15a580-004e-11eb-970b-6ad21706b57c.png)
发现端口还是随机生成的！
最后用8080端口请求数据，发现报错，且返回为空：
![image](https://user-images.githubusercontent.com/5664399/94344061-5990a480-004f-11eb-8a85-05548b973a25.png)
请大家指导~~~🌹

**Comment by sanren99999** [comment]
我知道问题在哪了，打扰大家了

**Comment by scottyungit** [comment]
> 我知道问题在哪了，打扰大家了

请问啥原因 我也遇到了

**Comment by CarlJi** [comment]
> > 我知道问题在哪了，打扰大家了
> 
> 请问啥原因 我也遇到了

要使用goc build 编译出来的二进制执行才行。

其实goc build/run/install 三个命令的设计理念是跟go build/run/install 靠齐的，大家可以映照着理解会轻松些。 @scottyungit

**Comment by scottyungit** [comment]
> > > 我知道问题在哪了，打扰大家了
> > 
> > 
> > 请问啥原因 我也遇到了
> 
> 要使用goc build 编译出来的二进制执行才行。
> 
> 其实goc build/run/install 三个命令的设计理念是跟go build/run/install 靠齐的，大家可以映照着理解会轻松些。 @scottyungit

奇怪 我就是在编译是 使用goc build的。

**Comment by CarlJi** [comment]
编译的产物是二进制，有了二进制直接执行它就可以了。

但我看你上面的截图，你是调用`goc build`之后，仍然通过`goc run .` 来执行的。
