### ISSUE TITLE
File copy strategy of `goc build` needs to be optimized

### ISSUE THREAD

**Issue by tongjingran** [qiniu/goc#126]
Some files like `unix socket` is not allowed to be copied. When project files contians these file, `goc build .` will return an error. The file copy strategy needs optimize.

**Comment by gavwu** [comment]
I am running into the same question, and it is tricky to find out the root cause (which in this case is socket file can not be copied).

**Comment by tongjingran** [comment]
> I am running into the same question, and it is tricky to find out the root cause (which in this case is socket file can not be copied).

i will fix it recently

**Comment by tongjingran** [comment]
> I am running into the same question, and it is tricky to find out the root cause (which in this case is socket file can not be copied).

@gavwu fixed!

**Comment by tongjingran** [comment]
new startegy can't copy all files in go1.13, revert.

**Comment by tongjingran** [comment]
fixed
