### ISSUE TITLE
profile --coverfile 选项支持支持 "not contains" 语义

### ISSUE THREAD

**Issue by wuduozhi** [qiniu/goc#134]
$ goc profile --address=http://127.0.0.1:9999  --coverfile="service*",'?!thrift_gen*'  -o=coverage.out

FATA Goc server http://127.0.0.1:7777 return an error: {"error":"failed to filter profile based on the patterns: [service* ?!thrift_gen*], error: filterProfile failed with pattern ?!thrift_gen* for profile git.byted.org/ee/lark/facade/sticker/database/abase_sticker_set.go, err: error parsing regexp: missing argument to repetition operator: `?`"}

可以看到，使用 ?!thrift_gen* 正则来排除 thrift_gen 下的文件时，就有报错了

**Comment by CarlJi** [comment]
Thanks for your feedback. This should be caused by the special of [Go regex syntax](https://github.com/google/re2/wiki/Syntax)

To improve user experience，I am thinking about we may provide a new flag like `exceptfile` to do this. ex:
``` shell
goc profile [--coverfile=pattern1] [--exceptfile=pattern1]
```

**Comment by wuduozhi** [comment]
Are you doing ?

**Comment by wuduozhi** [comment]
请问你们有完成的时间点了吗？

**Comment by CarlJi** [comment]
> 请问你们有完成的时间点了吗？

/assign @CarlJi 

I will handle it in this week.

**Comment by wuduozhi** [comment]
hello，请问一下，弄完了没有呀

**Comment by lyyyuna** [comment]
Negative lookahead is not supported by the official Golang regex engine: https://groups.google.com/g/golang-nuts/c/7qgSDWPIh_E, 
so add a `skipFile` flag is acceptable.
