### ISSUE TITLE
goc server 支持通过服务发现获取和运行是注册

### ISSUE THREAD

**Issue by wuduozhi** [qiniu/goc#140]
现在是在 goc build 的时候指定 ip:port，能否支持在服务启动的时候通过服务发现，来获取 goc server 的 ip:port ? 场景是 goc server 的 ip 无法固定，同时服务的编译和启动是分开的，有一次编译，多次运行的场景。

**Comment by CarlJi** [comment]
给goc server 配置个domain，是不是就行了?

**Comment by CarlJi** [comment]
No more further requests, closing it.
