### ISSUE TITLE
goc收集覆盖率时怎么获取代码总行数/覆盖行数

### ISSUE THREAD

**Issue by tang-xiao-zhuang** [qiniu/goc#160]
既然可以拿到覆盖率,那就肯定有覆盖行数和相应的总行数,这需要通过什么来获取呢

**Comment by tongjingran** [comment]
直接通过 `goc profile` 获取到的coverprofile数据如下形式：
`github.com/qiniu/goc/goc.go:21.13,23.2 1 1`
这里的内容就是通过类似上面的变量`CoverageVariableName`得到。其基本语义为
"**文件:起始行.起始列,结束行.结束列 该基本块中的语句数量 该基本块被执行到的次数**"
基于此，可计算覆盖行数和总行数。
目前goc仅提供最原始的coverprofile。

**Comment by tang-xiao-zhuang** [comment]
这样算是可以算出来,但是项目比较大,这样生成的文件去解析的话很不方便,效率很低,以后会推出直接获取总行数,覆盖行数吗?

**Comment by CarlJi** [comment]
这样是否方便呢? 一条命令就可以拿到总的statment数量  
`goc profile | awk '{result+=$2} END {print result}'`

> 这样算是可以算出来,但是项目比较大,这样生成的文件去解析的话很不方便,效率很低,以后会推出直接获取总行数,覆盖行数吗?

这句是希望`goc server` 提供一个API吗？单纯的行数，感觉需求有点小，你这边有更多的分析场景需求嘛？
