### ISSUE TITLE
goc profile will return FATA dial tcp xx.xx.xx.xx:36267: connect: connection refused

### ISSUE THREAD

**Issue by eyotang** [qiniu/goc#162]
**goc profile**
return FATA dial tcp xx.xx.xx.xx:36267: connect: connection refused

REASON:
no deregister to goc server while process exit

SOLUTION:
detect the signal. send deregister for all addresses to goc server to remove the service.

**Comment by CarlJi** [comment]
Hi @eyotang , thanks for your solution!
