### ISSUE TITLE
远程获取goc的内容，耗时很长并且无法获得正确的渲染

### ISSUE THREAD

**Issue by fifthszsu** [qiniu/goc#172]
在Goc Coverage的插件中，Goc server Url 配置了另一台host的地址（goc服务所在的host）
然后在host上面能看到链接信息，但是响应时间很长，需要10几s
对比host本地的监听只有100多ms
host本地的监听能够正常渲染被执行到的代码，但是远程链接过去的监听无法渲染到绿色的代码块（是turn on状态）

一开始怀疑是网络问题，但是两部机器互相ping都是只有100多ms。。请问是否是性能问题，能否改善一下

**Comment by CarlJi** [comment]
这里面的`Goc Coverage` 是指Goc 的VSCode插件吗？

问题描述我有点没明白. 上面的10+s的log 能贴下吗？

cc @lyyyuna

**Comment by CarlJi** [comment]
no more comments, closing
