### ISSUE TITLE
goc收集代码覆盖率数据跳动,方法执行没有被统计

### ISSUE THREAD

**Issue by tang-xiao-zhuang** [qiniu/goc#175]
项目中集成了goc,多次统计发现,一会是50.7%,一会是63%,其中涉及到2个go文件中的方法没有被统计,一会又一会没有,请问是什么问题(注: 每一分钟执行一次goc profile出现的问题)

**Comment by CarlJi** [comment]
goc profile 获取的数据都是实时的。建议还是实际确认下代码逻辑，看看代码是否应该被一直执行到。

以我们为例，在分布式场景下，即使是相同的集测，在不同场景和被测环境下执行，所覆盖到的代码也有可能是不一样的，因为其涉及到的时间、流量、延迟、实例等等因素。

@tang-xiao-zhuang
