### ISSUE TITLE
cannot connect to services when `goc profile` (IPv6)

### ISSUE THREAD

**Issue by uveege** [qiniu/goc#177]
**Original Question:**

in my environment, services are registered with address in `xxx_profile_listen_addr`, but it won't kick in :
```
INFO[2021-03-18T15:25:58+08:00][cover/server.go:140] the registered host api of service 172.17.0.1 is different with the real one ::1, here we choose the real one
[GIN] 2021/03/18 - 15:25:58 | 200 |     940.749µs |       ::1 | POST     "/v1/cover/register?name=api&address=http://172.17.0.1:35975"
```
`gin.Context.ClientIP`(pkg/cover/server.go:138) returns a IPv6 address, while actually my service only listens in IPv4:
```
# lsof -i:35975
COMMAND PID USER   FD   TYPE     DEVICE SIZE/OFF NODE NAME
api      25 root    3u  IPv4 4118769665      0t0  TCP *:35975 (LISTEN)
```
therefore, `goc profile` won't work:
```
# bin/goc profile
FATA Goc server http://127.0.0.1:7777 return an error: {"error":"failed to get profile from http://::1:35975, error Post \"http://::1:35975/v1/cover/profile\": dial tcp [::1]:35975: connect: connection refused"} 
```

**Advice from me:**
1. no need to check if realIP == host in registerService, just keep what get from users (pkg/cover/server.go:140)
2. or add a new flag for advice 1
3. or services should listen in IPv6 mode as well

hmmm..not sure which one is better, up to you guys :D

**Comment by uveege** [comment]
another weird thing is, when I run `goc register` in terminal, the `realIP` is 127.0.0.1,
but when I run in shell script, I got ::1

**Comment by CarlJi** [comment]
hi @uveege , based on [the information here,](https://github.com/gin-gonic/gin/issues/604#issuecomment-214758050) i am guessing your client is behind a proxy.

To enhance this scenario, i prefer to add a rule that only replace the IP when the ClientIP belongs to IPV4 model. Please review the linked PR.
