### ISSUE TITLE
goc无法编译

### ISSUE THREAD

**Issue by RicardoHa** [qiniu/goc#182]
报错信息：./goc: cannot execute binary file: Exec format error
换成go直接编译就可以
请问goc编译对项目的文件路径有什么要求吗？main方法所在文件一定要放在src下边嘛？以及main方法一定要命名为main.go嘛？
请问如下路径是否支持：

src
  --TestService
     --service
        --proxy
           --proxy,go
     --ortherCode
           --xx.go
其中main方法放在proxy.go中。 其他代码放在ortherCode中

**Comment by CarlJi** [comment]
`Exec format error` 这个错一般是二进制格式相关，比如在linux编译的二进制，拿到windows平台上用。
@RicardoHa 建议检查下。

**Comment by RicardoHa** [comment]
发现在x86下可以编译，arm下会有相关报错

**Comment by CarlJi** [comment]
我上面的说法，是指要检查下 goc这个二进制，是针对哪个平台编译出来的。不同的平台，选用的goc是不一样的。 @RicardoHa

**Comment by CarlJi** [comment]
没有进一步的反馈，关闭issue。
