### ISSUE TITLE
goc build . FATA Fail to build: fail to list package dependencies

### ISSUE THREAD

**Issue by sword-jin** [qiniu/goc#187]
很多docker images没有 bash，需要检测bash环境

![image](https://user-images.githubusercontent.com/11711621/117934208-039a1400-b335-11eb-9cfb-ca3b6b3129b2.png)

**Comment by CarlJi** [comment]
Good suggestion, we will enhance it. thanks @rrylee

**Comment by fananchong** [comment]
![image](https://user-images.githubusercontent.com/20277955/144703090-8052e200-f0eb-4123-bf25-27ad50f99879.png)

**Comment by fananchong** [comment]
![image](https://user-images.githubusercontent.com/20277955/144703398-e03cb433-e600-40a5-ab7f-392d4cf44d06.png)

**Comment by fananchong** [comment]
提示不友好

**Comment by CarlJi** [comment]
> 提示不友好

是否有具体建议呢？ @fananchong

**Comment by yuzg667** [comment]
使用goc命令编译，我也遇到了这个问题。问下如何解决。
`原go命令行：
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go  build -ldflags "$LDFlags" -o dist/dental
使用GOC的命令行,报错。具体如附图：
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 goc build --buildflags="-ldflags '$LDFlags'"  --center=10.10.1.52:7777 --agentport=:46593 --debug -o dist/dental
`
![image](https://user-images.githubusercontent.com/20694486/173973426-96cd00e2-5819-4475-bd66-cb6550112b01.png)

**Comment by deljuven** [comment]
遇到相同的问题 +1
如果不是 必须要要求 bash，可以考虑改成 /bin/sh 来替代 /bin/bash。
不然可能需要 goc 整理一个 dependency list，明确依赖的环境和 toolchain 都有哪些
