### ISSUE TITLE
Optimize the README file to give user a better way to install goc

### ISSUE THREAD

**Issue by CarlJi** [qiniu/goc#193]

**Comment by aditya28sarin** [comment]
Can you assign this issue to me?

**Comment by CarlJi** [comment]
/assign @aditya28sarin, 

Appreciate it very much if you can help. 

BTW, what's your idea to do this? my original thought is to provide a command like curl to download the latest release binary, extract it and move it into bin path. so that user can use `goc` after executing that directly.
