### ISSUE TITLE
qrcode of goc WeChat Group is expired

### ISSUE THREAD

**Issue by hick** [qiniu/goc#222]
很高兴今天找到 goc ,  搜索好久才发现这个应该是我需要的.  

加微信群的二维码过期了哈,   求更新---另外需要的话我进群以后我可以做一个自动更新入群二维码的脚本, 哈哈哈

对 goc 比较有想法和期待,  时间和能力允许的话期待能参与开发

**Comment by CarlJi** [comment]
微信群不便于维护，我们更倾向于接受大家的issue。欢迎大家提issue。
