### ISSUE TITLE
goc形式运行gopath项目报错，辛苦帮忙看下，谢谢！

### ISSUE THREAD

**Issue by wangyingsi** [qiniu/goc#247]
go命令运行正常，详细见截图：
![8ba0e39db0d650062414dffab74ebae](https://user-images.githubusercontent.com/33273904/142602425-6ff05967-b7d0-435f-8f76-26fc3ffbf76e.png)
goc的形式运行报错，详细见截图：
![581bd3db13f0fe32fe29337811fe4f5](https://user-images.githubusercontent.com/33273904/142602521-e306131b-7b7f-451e-99e2-97c0849e4baf.png)
代码结构：goctest/src/mian.go
main.go的代码如下：
package main

import (
    "fmt"
    "log"
    "net/http"
    "strings"
)

func sayhelloname(w http.ResponseWriter, r *http.Request) {
    r.ParseForm() //解析参数,默认是不会解析的。
    fmt.Println(r.Form)
    fmt.Println("path:", r.URL.Path)
    fmt.Println("scheme:", r.URL.Scheme)
    fmt.Println(r.Form["url_long"])
    for k, v := range r.Form {
        fmt.Println("key:", k)
        fmt.Println("value:", strings.Join(v, ","))
    }
    fmt.Fprintf(w, "hello, welcome you!") //这个字符串写入到w中，用于返回给客户端。
}
func main() {
    http.HandleFunc("/", sayhelloname)       //设置访问的路由
    err := http.ListenAndServe(":9090", nil) //设置监听的端口
    if err != nil {
        log.Fatal("ListenAndServe: ", err)
    }
}

**Comment by CarlJi** [comment]
@wangyingsi hi, what's your `go version`?

**Comment by wangyingsi** [comment]
1.12

**Comment by wangyingsi** [comment]
> @wangyingsi hi, what's your `go version`?

1.12

**Comment by wangyingsi** [comment]
> @wangyingsi hi, what's your `go version`?

![image](https://user-images.githubusercontent.com/33273904/142852697-2e87a292-acdb-40fd-9c8a-baf0ebe8eef8.png)
1.12.4
