### ISSUE TITLE
源码级的插桩，所以势必会破坏源码。所以 goc 采取的策略是首先把整个工程拷贝到临时目录,这里是指拷贝到临时目录就不影响源码构建了吗

### ISSUE THREAD

**Issue by wangjielalala** [qiniu/goc#253]
参考: https://www.lyyyuna.com/2021/12/12/how-to-collect-coverage-in-go/   @lyyyuna

**Comment by lyyyuna** [comment]
破坏源码 应理解为 对源码有改动。
临时目录的意图是，不想在原目录处变动使用者原来的代码。

**Comment by lyyyuna** [comment]
研究源码的化，看 v2 分支吧。
