### ISSUE TITLE
别的工程接入这个工具时需要做什么呢？

### ISSUE THREAD

**Issue by chaishare** [qiniu/goc#267]
我看到demo项目中，有一个这个文件，是所有的接入项目都需要具备这个文件吗
![image](https://user-images.githubusercontent.com/101385313/158146100-66cca682-696a-4235-a3a1-90aa28e631c5.png)

**Comment by CarlJi** [comment]
@chaishare 可以看看中文版的README哈，里面也有相关的博客建议原理。

**Comment by CarlJi** [comment]
no more comments, closing.
