### ISSUE TITLE
覆盖率数据解析失败

### ISSUE THREAD

**Issue by wo2653880** [qiniu/goc#271]
goc产物里面这两个地方不统一
![wecom-temp-1cc9dae20e1522938bfc6a309f2c26e4](https://user-images.githubusercontent.com/19966052/159270689-8d580fbd-03ec-4009-a0c0-2b1fd2295dd2.png)
![wecom-temp-79e74a36429eb7a2213559fe3b5622e7](https://user-images.githubusercontent.com/19966052/159270718-a7a7fab8-cda2-475f-a2fd-9b336ddaf849.png)

**Comment by CarlJi** [comment]
@wo2653880 这两份profile，渲染后的代码是怎样的呢？是否有明显区别？

**Comment by CarlJi** [comment]
原因还是代码版本不一致。
