### ISSUE TITLE
coverage block mismatch

### ISSUE THREAD

**Issue by chumincc** [qiniu/goc#279]
启动了两个服务，执行goc profile get收集时报如下错误：不匹配是什么原因？单个服务可正常收集

Goc server http://127.0.0.1:7777 return an error: {"error":"error merging main/main.go: coverage block mismatch: block #0 for main/main.go ({StartLine:12 StartCol:13 EndLine:16 EndCol:34 NumStmt:2 Count:1} mismatches {StartLine:9 StartCol:13 EndLine:14 EndCol:34 NumStmt:2 Count:1})"}

**Comment by CarlJi** [comment]
> 启动了两个服务，执行goc profile get收集时报如下错误：不匹配是什么原因？单个服务可正常收集
> 
> Goc server http://127.0.0.1:7777 return an error: {"error":"error merging main/main.go: coverage block mismatch: block #0 for main/main.go ({StartLine:12 StartCol:13 EndLine:16 EndCol:34 NumStmt:2 Count:1} mismatches {StartLine:9 StartCol:13 EndLine:14 EndCol:34 NumStmt:2 Count:1})"}

这种情况一般是这两个服务使用的代码，版本不一致导致的。 @chumincc

**Comment by chumincc** [comment]
> > 启动了两个服务，执行goc profile get收集时报如下错误：不匹配是什么原因？单个服务可正常收集
> > Goc server http://127.0.0.1:7777 return an error: {"error":"error merging main/main.go: coverage block mismatch: block #0 for main/main.go ({StartLine:12 StartCol:13 EndLine:16 EndCol:34 NumStmt:2 Count:1} mismatches {StartLine:9 StartCol:13 EndLine:14 EndCol:34 NumStmt:2 Count:1})"}
> 
> 这种情况一般是这两个服务使用的代码，版本不一致导致的。 @chumincc

我的设想是统计两个不同的服务，比如一个是消息服务，一个是搜索服务，通过命令生成总的覆盖率数据，两个服务的业务代是不一样的，不知道是否可以实现？@Carlji

**Comment by CarlJi** [comment]
可以。你这里本质是两个服务使用的同一份代码，其版本不一致，导致没法合并。

**Comment by CarlJi** [comment]
可以这样排查下:
1. 分别取这个服务的覆盖率结果: `goc profile --address=xxx >> 1.out`
2. 然后用各自的代码渲染: `go tool cover -html=1.out`
3. 比较渲染后的结果

**Comment by chumincc** [comment]
不是很理解这句话“两个服务使用的同一份代码”，启动了一个goc server，分开build，分别使用8000和8001启动了两个服务，代码是分开的，如下图
<img width="254" alt="image" src="https://user-images.githubusercontent.com/52067240/163752101-70e44d9a-01df-4c1c-887f-980fda009451.png">

**Comment by CarlJi** [comment]
就是说，你这个上下两份`main.go`文件有差异。

**Comment by chumincc** [comment]
不理解，正常两个不同的服务，main文件是不一样的。难道说集成收集的意思是同一个服务部署在多个地方，这个意思？而不是同一个服务器不是多个不同的服务。

**Comment by chumincc** [comment]
不知道为何产生这个问题，但是把注册中心重新部署，重新编译运行就好了，还是原来一样的项目结构

**Comment by HeartIsBeat** [comment]
我就一个服务，然后新增代码git pull，goc build重新部署了，goc merge报错：
level=fatal msg="failed to merge files: error merging gocovstudy/main.go: file block count for gocovstudy/main.go mismatches (9 vs 10)"
这是为啥？？
