### ISSUE TITLE
已修改注册中心端口，dial tcp 127.0.0.1:7777: connect: connection refused

### ISSUE THREAD

**Issue by chumincc** [qiniu/goc#280]
已启动注册中心端口为8888，
<img width="881" alt="image" src="https://user-images.githubusercontent.com/52067240/163942114-cec7189f-6c0c-42c7-b9d9-5d641bcfcbb4.png">
编译后启动显示连接不上，7777：
register address * failed, err: failed to register into coverage center, err:Post "http://127.0.0.1:7777/v1/cover/register?name=cmd&address=*": dial tcp 127.0.0.1:7777: connect: connection refused, response:

**Comment by CarlJi** [comment]
可以用 `goc build --center=xxx` 来编译 @chumincc

**Comment by chumincc** [comment]
已解决，感谢。
