### ISSUE TITLE
使用 goc build的应用 会自动添加 test.v的flag

### ISSUE THREAD

**Issue by Jun10ng** [qiniu/goc#289]
hi team：
我想请问下 使用goc build的应用 会自动添加 test.v的flag 吗？有什么办法避免

demo如下：

```
func main()  {
	if flag.Lookup("test.v")!=nil{
		fmt.Println("test.v")
		return
	}else {
		fmt.Println("no test.v")
	}
}
```

使用goc build上面代码后，会输出 “test.v”，有没有什么办法避免呢？我们借助 test.v 参数来执行单元测试脚本，比如：单元测试时，不执行某些资源初始化。

**Comment by CarlJi** [comment]
goc 底层使用的仍然是`go build`来做编译，其行为跟原生的一致，所以不会注入`test.v`。 @Jun10ng
