### ISSUE TITLE
问题咨询：能否把编译生成的二进制服务和goc-build分开

### ISSUE THREAD

**Issue by sz891016** [qiniu/goc#291]
请问是否支持在A节点上编译，然后把生成的二进制传输到B节点上启动，请求B节点接口，收集覆盖率呢？

**Comment by sz891016** [comment]
done

**Comment by CarlJi** [comment]
这里的"节点" 是指机器吗？ 如果是的话，那天生就支持啊。

和`go build`一样，`goc build`输出的也是二进制，二进制理论上是可以同架构系统下的任何地方执行的。当然在启动时，这个二进制需要与`goc server` 通信，所以只要保持这个通道畅通就可以了。 @sz891016

**Comment by CarlJi** [comment]
no more comments, closing.
