### ISSUE TITLE
goc profile

### ISSUE THREAD

**Issue by songwenqin-vip** [qiniu/goc#295]
What's the reason of no profiles?

root@90464575afd4:/go# goc profile
FATA Goc server http://127.0.0.1:7777 return an error: {"error":"no profiles"} 

root@90464575afd4:/go# goc list
{"sample-manager":["http://10.0.1.4:45678"]}

**Comment by songwenqin-vip** [comment]
I found goc register revise the IP address, using docker gateway ip.

**Comment by HeartIsBeat** [comment]
请问 你这个goc profile获取到覆盖率，最后怎么解决的？
