### ISSUE TITLE
fail to curl

### ISSUE THREAD

**Issue by debbyzang** [qiniu/goc#307]
[root@localhost zfs]# curl -s -L "https://github.com/qiniu/goc/releases/latest" | sed -nE 's!.*"([^"]*-linux-386.tar.gz)".*!https://github.com\1!p' | xargs -n 1 curl -L  | tar -zx && chmod +x goc && mv goc /usr/local/bin

curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by CarlJi** [comment]
hi @debbyzang , i have fixed this, please try again. Thanks.
