### ISSUE TITLE
goc profile in multi-instance environment

### ISSUE THREAD

**Issue by mashraf09** [qiniu/goc#312]
I have a multi-instance  environment, an application and its replica both are running as load balanacer and serving multiple requests and when I get coverage using ```goc profile --center=http://127.0.0.1:7779 --service=consumer-logger > coverage.out && go tool cover -html=coverage.out``` it gives complete coverage from both instances, but when one instance goes down (or shutdown manually) its coverage profile is also removed, `goc profile` returns only the coverage results of other instance. Is there any possibility that when an instance goes down its profile remains and it does not call v1/cover/remove 

goc server logs:
```
goc-server_1               | [GIN-debug] POST   /v1/cover/remove          --> github.com/qiniu/goc/pkg/cover.(*server).removeServices-fm (3 handlers)
goc-server_1               | [GIN-debug] Listening and serving HTTP on localhost:7779
goc-server_1               | [GIN] 2022/10/06 - 07:44:35 | 200 |    7.913742ms |       127.0.0.1 | POST     "/v1/cover/register?name=consumer-logger&address=http://172.20.0.1:40675"
goc-server_1               | [GIN] 2022/10/06 - 07:44:35 | 200 |    6.987119ms |       127.0.0.1 | POST     "/v1/cover/register?name=consumer-logger&address=http://172.20.0.1:36741"
goc-server_1               | [GIN] 2022/10/06 - 08:17:54 | 200 |    1.540015ms |       127.0.0.1 | POST     "/v1/cover/profile"
goc-server_1               | [GIN] 2022/10/06 - 08:22:24 | 200 |    1.179782ms |       127.0.0.1 | POST     "/v1/cover/profile"
goc-server_1               | [GIN] 2022/10/06 - 08:24:01 | 200 |      1.1164ms |       127.0.0.1 | POST     "/v1/cover/profile"
goc-server_1               | [GIN] 2022/10/06 - 08:25:22 | 200 |     852.182µs |       127.0.0.1 | POST     "/v1/cover/profile"
goc-server_1               | [GIN] 2022/10/06 - 08:37:26 | 200 |    1.954155ms |       127.0.0.1 | POST     "/v1/cover/remove"
goc-server_1               | [GIN] 2022/10/06 - 08:37:37 | 417 |      65.555µs |       127.0.0.1 | POST     "/v1/cover/profile"

```

**Comment by CarlJi** [comment]
@mashraf09  currently, whenever we call `goc profile`, it will pull data from the applications under test, and `goc` itself didn't store any data. In other words, it was by design for your scenario.

**Comment by mashraf09** [comment]
@CarlJi got it, thanks
