### ISSUE TITLE
精测测试如何使用goc

### ISSUE THREAD

**Issue by cnlydia** [qiniu/goc#313]
想在运行一个测试用例后，得到这个用例涉及到的代码，但是现在只知道从profile生成的cov里面的count读出来变化，这样代码量大的情况下，读取每一行代码段count的耗时太长，有没有其他更好地方式呢？

**Comment by CarlJi** [comment]
具体耗时多久呢？

如果读取count都耗时挺久，那针对每个文件的变动抽code block会更耗时吧，在你这个场景里是不是就没法接受了？

**Comment by cnlydia** [comment]
> 

profile 中有13646行，然后去比对下一次的profile文件里面对应的count是否有变动，大概耗时需要一分半钟，如果有100个用例的话，就需要将近2个半小时了 :(

**Comment by CarlJi** [comment]
[goc v2](https://github.com/qiniu/goc/tree/v2#5-watch-%E6%A8%A1%E5%BC%8F) 有watch的能力，可以主动推送覆盖率变化，可以尝试下。

**Comment by cnlydia** [comment]
之前是直接使用linux命令去对比文件的，比较原始，现在改成了用python的difflib去读就快了很多，感谢 :)
