### ISSUE TITLE
不同代码版本的覆盖率文件合并

### ISSUE THREAD

**Issue by kangyingjie** [qiniu/goc#320]
背景：我们目前自动化测试用例还比较少，以人工测试为主，想看下人工测试的代码覆盖情况。
目前的测试工作流程: 1提测 -> 2测试/反馈问题 -> 3修复bug/发版 -> (重复2,3) -> 4测试完成。
现在加入统计代码覆盖率，人工测试因为用例很多，不能像自动化测试一样重放。想在步骤3`修复bug重新发版`时， 合并之前的覆盖率文件。实际发现会报错，提示文件行数不一致，无法合并。

想了解下为了这种统计目标有没有推荐的方案。🙏

**Comment by KevinFang3** [comment]
bro你后来找到方案没
