### ISSUE TITLE
goc build 失败 fail to generate new go.mod xxx unknown directive: toolchain

### ISSUE THREAD

**Issue by zhangwk02** [qiniu/goc#388]
FATA Fail to build: fail to generate new go.mod: /tmp/goc-build-2c7108a515c0/go.mod:5: unknown directive: toolchain

用 go build 可以编译，go 版本 1.22.1; 但是用 goc build 就报上述错误，不知道啥原因？

**Comment by CarlJi** [comment]
你用源码重新编一版goc试试呢?

**Comment by zhangwk02** [comment]
> 你用源码重新编一版goc试试呢?
试了一下也不行，是不是 goc 对 1.20+ go 版本不兼容？
原来是 1.20 以前的go 版本build 也会报错，升级 go 版本解决了
