### ISSUE TITLE
goc should support got single project coverage  by "goc profile"，Now it's getting all projects.

### ISSUE THREAD

**Issue by Alanfight** [qiniu/goc#66]
As the title， thanks

**Comment by lyyyuna** [comment]
@AlanFightting what do you mean by single project? One service? Or one single project consists of several services (as a collection of one server)?

**Comment by AlanFightting** [comment]
yes,  I want got one service  from specified register center

**Comment by tongjingran** [comment]
put it on the agenda

**Comment by tongjingran** [comment]
@Alanfight goc profile support getting the profile of specific services or addresses. You can use `goc profile --service=a,b,c` or `goc profile --address=http://127.0.0.1:1234,http://127.0.0.1:5678` to get what you want. All the available services and addresses are shown in `goc list`.

**Comment by Alanfight** [comment]
When will a version be released

**Comment by lyyyuna** [comment]
@Alanfight , we have released the v1.2.0,  can you help to test the new flags mentioned by @tongjingran ?

**Comment by CarlJi** [comment]
feature provided as `goc profile [--address|--server]`. Close this issue.
