### ISSUE TITLE
Errors should show in command instead of output files when get a profile

### ISSUE THREAD

**Issue by tongjingran** [qiniu/goc#72]
If errors occur when we use `goc profile --output output.txt` to get a profile, we found that there is nothing warning on the terminal screen. But the errors appeared unexpectedly in the output file.

**Comment by CarlJi** [comment]
It's better to provide the logs to show the details for your scenario, as:
`goc profile` vs `goc profile --output output.txt`

**Comment by tongjingran** [comment]
Use `goc profile`. if an error occurs, the terminal shows
`{"error":"Get http://10.100.10.13:32413/v1/cover/profile: dial tcp 10.100.10.13:32413: connect: connection refused"}`
Use `goc profile -o output.txt`. If an error occurs , there's nothing print the terminal. We found that the error info would write to the output.txt directly. 
Errors should show in terminal before writing them into the output file.
