### ISSUE TITLE
goc build err but i can't understand , I need  your help

### ISSUE THREAD

**Issue by wzh521** [qiniu/goc#73]
"github.com/sparrc/go-ping"
   I use goPing library in my projects . when i run the command "goc build ." error occurs but i can't understand.

mistake 
./http_cover_apis_auto_generated.go:2135:89: undefined: cache_343664633233633838353763.GoCacheCover_0_34636232323162626631
./http_cover_apis_auto_generated.go:2137:88: undefined: cache_343664633233633838353763.GoCacheCover_1_34636232323162626631
./http_cover_apis_auto_generated.go:3978:17: undefined: cache_343664633233633838353763.GoCacheCover_0_34636232323162626631
./http_cover_apis_auto_generated.go:3980:17: undefined: cache_343664633233633838353763.GoCacheCover_1_34636232323162626631
FATA Fail to build: fail to execute: [/bin/bash -c go build  -o /home/test .], err: exit status 2

**Comment by wzh521** [comment]
INFO[2020-07-14T10:02:55+08:00][logrus/entry.go:313] cache cover exist: github.com/panjf2000/ants/cache_373732376636353838396563 
INFO[2020-07-14T10:02:55+08:00][logrus/entry.go:313] cache cover exist: github.com/pierrec/lz4/cache_373232643464303736396661 
INFO[2020-07-14T10:02:56+08:00][logrus/entry.go:313] cache cover exist: golang.org/x/net/cache_343664633233633838353763 

i found id  is same , but when i remove goping  id is not same .

**Comment by CarlJi** [comment]
Thanks @wzh521 

`http_cover_apis_auto_generated.go` file is auto generated by goc, and basically is hidden for users. I am guessing maybe you are trying the `goc cover` command? if yes, please be careful, it will contaminate your code.

For your question, you can try to clean your workspace first and use `go build` to make sure the project can be compiled successfully. then use `goc build .` to try it again.

if problem persists, please turn on `--debug` flag, and provide the full logs for us.

**Comment by wzh521** [comment]
Thanks @ CarlJi
the proplem stil exists , i don't konw how to solve

09:33:16 09:33:16 time="2020-07-15T09:33:15+08:00" level=info msg="Working directory: /home/goProjects/src/Pick/pick" file="[logrus/entry.go:313]"
09:33:16 09:33:16 time="2020-07-15T09:33:15+08:00" level=info msg="go list cmd is: [/bin/bash -c go list -json ./...]" file="[logrus/entry.go:313]"
09:33:16 09:33:16 time="2020-07-15T09:33:15+08:00" level=info msg="Tmp project generated in: /tmp/goc-build-ea6aef3d380f" file="[logrus/entry.go:313]"
09:33:16 09:33:16 time="2020-07-15T09:33:15+08:00" level=info msg="mod project? false" file="[logrus/entry.go:313]"
09:33:17 09:33:17 time="2020-07-15T09:33:16+08:00" level=info msg="New workingdir in tmp directory in: /tmp/goc-build-ea6aef3d380f/src/Pick/pick" file="[logrus/entry.go:313]"
09:33:17 09:33:17 time="2020-07-15T09:33:16+08:00" level=info msg="New GOPATH: /tmp/goc-build-ea6aef3d380f:/home/goProjects" file="[logrus/entry.go:313]"
09:33:17 09:33:17 time="2020-07-15T09:33:16+08:00" level=info msg="go list cmd is: [/bin/bash -c go list -json ./...]" file="[logrus/entry.go:313]"
09:33:17 09:33:17 time="2020-07-15T09:33:17+08:00" level=info msg="handle package: github.com/valyala/fasthttp/examples/fileserver" file="[logrus/entry.go:313]"
09:33:18 09:33:18 time="2020-07-15T09:33:17+08:00" level=info msg="handle package: github.com/Shopify/sarama/examples/http_server" file="[logrus/entry.go:313]"
09:33:22 09:33:22 time="2020-07-15T09:33:21+08:00" level=info msg="handle package: github.com/golang/snappy/cmd/snappytool" file="[logrus/entry.go:313]"
09:33:22 09:33:22 time="2020-07-15T09:33:21+08:00" level=info msg="handle package: github.com/pierrec/lz4/cmd/lz4c" file="[logrus/entry.go:313]"
09:33:22 09:33:22 time="2020-07-15T09:33:21+08:00" level=info msg="cache cover exist: github.com/pierrec/lz4/cache_373232643464303736396661" file="[logrus/entry.go:313]"
09:33:22 09:33:22 time="2020-07-15T09:33:21+08:00" level=info msg="handle package: github.com/mailru/easyjson/easyjson" file="[logrus/entry.go:313]"
09:33:22 09:33:22 time="2020-07-15T09:33:21+08:00" level=info msg="handle package: github.com/rcrowley/go-metrics/cmd/metrics-bench" file="[logrus/entry.go:313]"
09:33:22 09:33:22 time="2020-07-15T09:33:21+08:00" level=info msg="handle package: github.com/rcrowley/go-metrics/cmd/never-read" file="[logrus/entry.go:313]"
09:33:22 09:33:22 time="2020-07-15T09:33:21+08:00" level=info msg="handle package: github.com/yuin/gopher-lua/cmd/glua" file="[logrus/entry.go:313]"
09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="handle package: github.com/Shopify/sarama/tools/kafka-console-consumer" file="[logrus/entry.go:313]"
09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="cache cover exist: github.com/klauspost/compress/zstd/cache_323139396362303938666562" file="[logrus/entry.go:313]"
09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="cache cover exist: github.com/pierrec/lz4/cache_373232643464303736396661" file="[logrus/entry.go:313]"
09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="cache cover exist: golang.org/x/net/cache_343664633233633838353763" file="[logrus/entry.go:313]"
09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="handle package: github.com/Shopify/sarama/tools/kafka-console-partitionconsumer" file="[logrus/entry.go:313]"
09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="cache cover exist: github.com/klauspost/compress/zstd/cache_323139396362303938666562" file="[logrus/entry.go:313]"
09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="cache cover exist: github.com/pierrec/lz4/cache_373232643464303736396661" file="[logrus/entry.go:313]"
09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="cache cover exist: golang.org/x/net/cache_343664633233633838353763" file="[logrus/entry.go:313]"
09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="handle package: github.com/valyala/fasthttp/examples/helloworldserver" file="[logrus/entry.go:313]"
09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="handle package: github.com/rcrowley/go-metrics/cmd/metrics-example" file="[logrus/entry.go:313]"
09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="handle package: Pick/pick/devicemanager/resource/functionPluginFile" file="[logrus/entry.go:313]"
09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="handle package: github.com/Shopify/sarama/tools/kafka-producer-performance" file="[logrus/entry.go:313]"
09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="cache cover exist: github.com/klauspost/compress/zstd/cache_323139396362303938666562" file="[logrus/entry.go:313]"
09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="cache cover exist: github.com/pierrec/lz4/cache_373232643464303736396661" file="[logrus/entry.go:313]"
09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="cache cover exist: golang.org/x/net/cache_343664633233633838353763" file="[logrus/entry.go:313]"
09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="handle package: github.com/soniah/gosnmp/examples" file="[logrus/entry.go:313]"
09:33:41 09:33:41 time="2020-07-15T09:33:39+08:00" level=info msg="handle package: github.com/shiena/ansicolor/ansicolor" file="[logrus/entry.go:313]"
09:33:41 09:33:41 time="2020-07-15T09:33:39+08:00" level=info msg="handle package: Pick/pick" file="[logrus/entry.go:313]"
09:33:42 09:33:42 time="2020-07-15T09:33:41+08:00" level=info msg="cache cover exist: github.com/klauspost/compress/zstd/cache_323139396362303938666562" file="[logrus/entry.go:313]"
09:33:42 09:33:42 time="2020-07-15T09:33:42+08:00" level=info msg="cache cover exist: github.com/pierrec/lz4/cache_373232643464303736396661" file="[logrus/entry.go:313]"
09:33:43 09:33:43 time="2020-07-15T09:33:43+08:00" level=info msg="cache cover exist: golang.org/x/net/cache_343664633233633838353763" file="[logrus/entry.go:313]"
09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="handle package: github.com/Shopify/sarama/tools/kafka-console-producer" file="[logrus/entry.go:313]"
09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="cache cover exist: github.com/klauspost/compress/zstd/cache_323139396362303938666562" file="[logrus/entry.go:313]"
09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="cache cover exist: github.com/pierrec/lz4/cache_373232643464303736396661" file="[logrus/entry.go:313]"
09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="cache cover exist: golang.org/x/net/cache_343664633233633838353763" file="[logrus/entry.go:313]"
09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="handle package: github.com/valyala/fasthttp/examples/multidomain" file="[logrus/entry.go:313]"
09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="handle package: github.com/Shopify/sarama/examples/sasl_scram_client" file="[logrus/entry.go:313]"
09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="cache cover exist: github.com/klauspost/compress/zstd/cache_323139396362303938666562" file="[logrus/entry.go:313]"
09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="cache cover exist: github.com/pierrec/lz4/cache_373232643464303736396661" file="[logrus/entry.go:313]"
09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="cache cover exist: golang.org/x/net/cache_343664633233633838353763" file="[logrus/entry.go:313]"
09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="handle package: github.com/Shopify/sarama/examples/consumergroup" file="[logrus/entry.go:313]"
09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="cache cover exist: github.com/klauspost/compress/zstd/cache_323139396362303938666562" file="[logrus/entry.go:313]"
09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="cache cover exist: github.com/pierrec/lz4/cache_373232643464303736396661" file="[logrus/entry.go:313]"
09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="cache cover exist: golang.org/x/net/cache_343664633233633838353763" file="[logrus/entry.go:313]"
09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="handle package: github.com/panjf2000/ants/examples" file="[logrus/entry.go:313]"
09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="cache cover exist: github.com/panjf2000/ants/cache_373732376636353838396563" file="[logrus/entry.go:313]"
09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="Go building in temp..." file="[logrus/entry.go:358]"
09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="go build cmd is: [/bin/bash -c go build  -o /home/goProjects/src/Pick/pick/pick .]" file="[logrus/entry.go:313]"
09:33:53 09:33:53 # Pick/pick
09:33:53 09:33:53 ./http_cover_apis_auto_generated.go:2377:89: undefined: cache_343664633233633838353763.GoCacheCover_0_34636232323162626631
09:33:53 09:33:53 ./http_cover_apis_auto_generated.go:2379:88: undefined: cache_343664633233633838353763.GoCacheCover_1_34636232323162626631
09:33:53 09:33:53 ./http_cover_apis_auto_generated.go:4448:17: undefined: cache_343664633233633838353763.GoCacheCover_0_34636232323162626631
09:33:53 09:33:53 ./http_cover_apis_auto_generated.go:4450:17: undefined: cache_343664633233633838353763.GoCacheCover_1_34636232323162626631
09:33:53 09:33:53 time="2020-07-15T09:33:52+08:00" level=error msg="go build failed. The error is: exit status 2" file="[logrus/entry.go:313]"
09:33:53 09:33:53 time="2020-07-15T09:33:52+08:00" level=fatal msg="Fail to build: fail to execute: [/bin/bash -c go build  -o /home/goProjects/src/Pick/pick/pick .], err: exit status 2" file="[logrus/entry.go:313]"
09:33:53 09:33:53 Error: goc build error! Please run 'go build' before commit codes

**Comment by wzh521** [comment]
> Thanks @ CarlJi
> the proplem stil exists , i don't konw how to solve
> 
> 09:33:16 09:33:16 time="2020-07-15T09:33:15+08:00" level=info msg="Working directory: /home/goProjects/src/Pick/pick" file="[logrus/entry.go:313]"
> 09:33:16 09:33:16 time="2020-07-15T09:33:15+08:00" level=info msg="go list cmd is: [/bin/bash -c go list -json ./...]" file="[logrus/entry.go:313]"
> 09:33:16 09:33:16 time="2020-07-15T09:33:15+08:00" level=info msg="Tmp project generated in: /tmp/goc-build-ea6aef3d380f" file="[logrus/entry.go:313]"
> 09:33:16 09:33:16 time="2020-07-15T09:33:15+08:00" level=info msg="mod project? false" file="[logrus/entry.go:313]"
> 09:33:17 09:33:17 time="2020-07-15T09:33:16+08:00" level=info msg="New workingdir in tmp directory in: /tmp/goc-build-ea6aef3d380f/src/Pick/pick" file="[logrus/entry.go:313]"
> 09:33:17 09:33:17 time="2020-07-15T09:33:16+08:00" level=info msg="New GOPATH: /tmp/goc-build-ea6aef3d380f:/home/goProjects" file="[logrus/entry.go:313]"
> 09:33:17 09:33:17 time="2020-07-15T09:33:16+08:00" level=info msg="go list cmd is: [/bin/bash -c go list -json ./...]" file="[logrus/entry.go:313]"
> 09:33:17 09:33:17 time="2020-07-15T09:33:17+08:00" level=info msg="handle package: github.com/valyala/fasthttp/examples/fileserver" file="[logrus/entry.go:313]"
> 09:33:18 09:33:18 time="2020-07-15T09:33:17+08:00" level=info msg="handle package: github.com/Shopify/sarama/examples/http_server" file="[logrus/entry.go:313]"
> 09:33:22 09:33:22 time="2020-07-15T09:33:21+08:00" level=info msg="handle package: github.com/golang/snappy/cmd/snappytool" file="[logrus/entry.go:313]"
> 09:33:22 09:33:22 time="2020-07-15T09:33:21+08:00" level=info msg="handle package: github.com/pierrec/lz4/cmd/lz4c" file="[logrus/entry.go:313]"
> 09:33:22 09:33:22 time="2020-07-15T09:33:21+08:00" level=info msg="cache cover exist: github.com/pierrec/lz4/cache_373232643464303736396661" file="[logrus/entry.go:313]"
> 09:33:22 09:33:22 time="2020-07-15T09:33:21+08:00" level=info msg="handle package: github.com/mailru/easyjson/easyjson" file="[logrus/entry.go:313]"
> 09:33:22 09:33:22 time="2020-07-15T09:33:21+08:00" level=info msg="handle package: github.com/rcrowley/go-metrics/cmd/metrics-bench" file="[logrus/entry.go:313]"
> 09:33:22 09:33:22 time="2020-07-15T09:33:21+08:00" level=info msg="handle package: github.com/rcrowley/go-metrics/cmd/never-read" file="[logrus/entry.go:313]"
> 09:33:22 09:33:22 time="2020-07-15T09:33:21+08:00" level=info msg="handle package: github.com/yuin/gopher-lua/cmd/glua" file="[logrus/entry.go:313]"
> 09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="handle package: github.com/Shopify/sarama/tools/kafka-console-consumer" file="[logrus/entry.go:313]"
> 09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="cache cover exist: github.com/klauspost/compress/zstd/cache_323139396362303938666562" file="[logrus/entry.go:313]"
> 09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="cache cover exist: github.com/pierrec/lz4/cache_373232643464303736396661" file="[logrus/entry.go:313]"
> 09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="cache cover exist: golang.org/x/net/cache_343664633233633838353763" file="[logrus/entry.go:313]"
> 09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="handle package: github.com/Shopify/sarama/tools/kafka-console-partitionconsumer" file="[logrus/entry.go:313]"
> 09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="cache cover exist: github.com/klauspost/compress/zstd/cache_323139396362303938666562" file="[logrus/entry.go:313]"
> 09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="cache cover exist: github.com/pierrec/lz4/cache_373232643464303736396661" file="[logrus/entry.go:313]"
> 09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="cache cover exist: golang.org/x/net/cache_343664633233633838353763" file="[logrus/entry.go:313]"
> 09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="handle package: github.com/valyala/fasthttp/examples/helloworldserver" file="[logrus/entry.go:313]"
> 09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="handle package: github.com/rcrowley/go-metrics/cmd/metrics-example" file="[logrus/entry.go:313]"
> 09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="handle package: Pick/pick/devicemanager/resource/functionPluginFile" file="[logrus/entry.go:313]"
> 09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="handle package: github.com/Shopify/sarama/tools/kafka-producer-performance" file="[logrus/entry.go:313]"
> 09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="cache cover exist: github.com/klauspost/compress/zstd/cache_323139396362303938666562" file="[logrus/entry.go:313]"
> 09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="cache cover exist: github.com/pierrec/lz4/cache_373232643464303736396661" file="[logrus/entry.go:313]"
> 09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="cache cover exist: golang.org/x/net/cache_343664633233633838353763" file="[logrus/entry.go:313]"
> 09:33:22 09:33:22 time="2020-07-15T09:33:22+08:00" level=info msg="handle package: github.com/soniah/gosnmp/examples" file="[logrus/entry.go:313]"
> 09:33:41 09:33:41 time="2020-07-15T09:33:39+08:00" level=info msg="handle package: github.com/shiena/ansicolor/ansicolor" file="[logrus/entry.go:313]"
> 09:33:41 09:33:41 time="2020-07-15T09:33:39+08:00" level=info msg="handle package: Pick/pick" file="[logrus/entry.go:313]"
> 09:33:42 09:33:42 time="2020-07-15T09:33:41+08:00" level=info msg="cache cover exist: github.com/klauspost/compress/zstd/cache_323139396362303938666562" file="[logrus/entry.go:313]"
> 09:33:42 09:33:42 time="2020-07-15T09:33:42+08:00" level=info msg="cache cover exist: github.com/pierrec/lz4/cache_373232643464303736396661" file="[logrus/entry.go:313]"
> 09:33:43 09:33:43 time="2020-07-15T09:33:43+08:00" level=info msg="cache cover exist: golang.org/x/net/cache_343664633233633838353763" file="[logrus/entry.go:313]"
> 09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="handle package: github.com/Shopify/sarama/tools/kafka-console-producer" file="[logrus/entry.go:313]"
> 09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="cache cover exist: github.com/klauspost/compress/zstd/cache_323139396362303938666562" file="[logrus/entry.go:313]"
> 09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="cache cover exist: github.com/pierrec/lz4/cache_373232643464303736396661" file="[logrus/entry.go:313]"
> 09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="cache cover exist: golang.org/x/net/cache_343664633233633838353763" file="[logrus/entry.go:313]"
> 09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="handle package: github.com/valyala/fasthttp/examples/multidomain" file="[logrus/entry.go:313]"
> 09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="handle package: github.com/Shopify/sarama/examples/sasl_scram_client" file="[logrus/entry.go:313]"
> 09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="cache cover exist: github.com/klauspost/compress/zstd/cache_323139396362303938666562" file="[logrus/entry.go:313]"
> 09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="cache cover exist: github.com/pierrec/lz4/cache_373232643464303736396661" file="[logrus/entry.go:313]"
> 09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="cache cover exist: golang.org/x/net/cache_343664633233633838353763" file="[logrus/entry.go:313]"
> 09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="handle package: github.com/Shopify/sarama/examples/consumergroup" file="[logrus/entry.go:313]"
> 09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="cache cover exist: github.com/klauspost/compress/zstd/cache_323139396362303938666562" file="[logrus/entry.go:313]"
> 09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="cache cover exist: github.com/pierrec/lz4/cache_373232643464303736396661" file="[logrus/entry.go:313]"
> 09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="cache cover exist: golang.org/x/net/cache_343664633233633838353763" file="[logrus/entry.go:313]"
> 09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="handle package: github.com/panjf2000/ants/examples" file="[logrus/entry.go:313]"
> 09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="cache cover exist: github.com/panjf2000/ants/cache_373732376636353838396563" file="[logrus/entry.go:313]"
> 09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="Go building in temp..." file="[logrus/entry.go:358]"
> 09:33:44 09:33:44 time="2020-07-15T09:33:44+08:00" level=info msg="go build cmd is: [/bin/bash -c go build -o /home/goProjects/src/Pick/pick/pick .]" file="[logrus/entry.go:313]"
> 09:33:53 09:33:53 # Pick/pick
> 09:33:53 09:33:53 ./http_cover_apis_auto_generated.go:2377:89: undefined: cache_343664633233633838353763.GoCacheCover_0_34636232323162626631
> 09:33:53 09:33:53 ./http_cover_apis_auto_generated.go:2379:88: undefined: cache_343664633233633838353763.GoCacheCover_1_34636232323162626631
> 09:33:53 09:33:53 ./http_cover_apis_auto_generated.go:4448:17: undefined: cache_343664633233633838353763.GoCacheCover_0_34636232323162626631
> 09:33:53 09:33:53 ./http_cover_apis_auto_generated.go:4450:17: undefined: cache_343664633233633838353763.GoCacheCover_1_34636232323162626631
> 09:33:53 09:33:53 time="2020-07-15T09:33:52+08:00" level=error msg="go build failed. The error is: exit status 2" file="[logrus/entry.go:313]"
> 09:33:53 09:33:53 time="2020-07-15T09:33:52+08:00" level=fatal msg="Fail to build: fail to execute: [/bin/bash -c go build -o /home/goProjects/src/Pick/pick/pick .], err: exit status 2" file="[logrus/entry.go:313]"
> 09:33:53 09:33:53 Error: goc build error! Please run 'go build' before commit codes

@CarlJi

**Comment by lyyyuna** [comment]
@wzh521 hi，from the goc debug log, I can get the following information:

1. `GOPATH=home/goProjects`
2. Your project is built with `GO111MODULE="off"`
3. Your project is in `/home/goProjects/src/Pick/pick`, and seems there is a lot of main packages in `Pick/pick`
4. It seems that you are using an old or self-built goc, as the logrus logs a wrong file name (a known bug, logrus<1.5 with go1.14)

We cannot find the root cause now with the above info, so:

1. If possible, can you show us the project structure in `/home/goProjects/src/Pick/pick`? (with the tree command)
2. If possible, can you attach the `go list -json ./...` command output in `/home/goProjects/src/Pick/pick`?
2. Can you use the latest goc version and try again? The latest version should be 1.2.1, you can download it in [https://github.com/qiniu/goc/releases/tag/v1.2.1](https://github.com/qiniu/goc/releases/tag/v1.2.1), you can use the `goc version` command to double confirm it.

**Comment by wzh521** [comment]
@lyyyuna 
Thank you for your help.I solved this problem by deleting redundant main packages. I will try the new version later，If the problem recurs, can I contact you again？

**Comment by lyyyuna** [comment]
@wzh521 sure~
