### ISSUE TITLE
go get报错：tmpfolder.go:86:5: undefined: errors.Is；roundtripper.go:48:16: undefined: errors.Unwrap

### ISSUE THREAD

**Issue by seven1999** [qiniu/goc#84]
xxxxMacBook-Pro:~ xxxx$ go get -u github.com/qiniu/goc
# github.com/hashicorp/go-retryablehttp
xxx/src/github.com/hashicorp/go-retryablehttp/roundtripper.go:48:16: undefined: errors.Unwrap
# github.com/qiniu/goc/pkg/build
xxxx/src/github.com/qiniu/goc/pkg/build/tmpfolder.go:86:5: undefined: errors.Is

**Comment by lyyyuna** [comment]
@seven1999 , what's your go version?
this new function `errors.Unwrap` needs go1.13+

**Comment by CarlJi** [comment]
Please refer to the guide: https://github.com/qiniu/goc#installation. Closing it. Feel free to reopen or create a new issue if you have further questions again @seven1999
