### ISSUE TITLE
cannot build if go.mod has relative path 'replace' directive

### ISSUE THREAD

**Issue by dmc420** [qiniu/goc#92]
项目比较大，各种依赖很复杂，有十几个文件，之前都是用makefile编译的
执行goc build .报错
go: $path/$module@v0.0.0-20200804122736-5634267498a2: parsing $path/go.mod: open $path/go.mod: no such file or directory
FATA Fail to build: fail to execute: [/bin/bash -c go build  -o $path/$program .], err: exit status 1
试了下用go build .可以成功编译

**Comment by lyyyuna** [comment]
能否加上 --debug 再运行一次？--debug 会输出所有日志

另外，有些问题，
1. 我看你这是使用了 go.mod，依赖全部由 gomodule 管理吗？
2. 是单个 go mod 工程，还是有使用 replace 来组合多个 go mod 工程？replace 相对路径还未支持。
3. 这里的 `$path/$module` 是本身就这样，还是为了故意隐去的？

**Comment by dmc420** [comment]
> 能否加上 --debug 再运行一次？--debug 会输出所有日志
> 
> 另外，有些问题，
> 
> 1. 我看你这是使用了 go.mod，依赖全部由 gomodule 管理吗？
> 2. 是单个 go mod 工程，还是有使用 replace 来组合多个 go mod 工程？replace 相对路径还未支持。
> 3. 这里的 `$path/$module` 是本身就这样，还是隐去了？

感谢，就是go.mod里面的replace使用的相对路径，改成绝对路径就可以编译成功了，

**Comment by lyyyuna** [comment]
@dmc420

**Comment by lyyyuna** [comment]
@dmc420 新的release还未发布，可以用最新 commit 做测试，支持了相对路径的 go.mod replace。

**Comment by dmc420** [comment]
> @dmc420 新的release还未发布，可以用最新 commit 做测试，支持了相对路径的 go.mod replace。

好的，非常感谢

**Comment by IcePaper4coding** [comment]
您好 发现如果有modules,txt 的话，只替换mod 也会报错

**Comment by IcePaper4coding** [comment]
您好 发现如果有modules,txt 的话，只替换mod 也会报错
